In [1]:
import numpy as np

In [3]:
lst1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(lst1)
print(type(nd1),nd1)

<class 'numpy.ndarray'> [3.14 2.17 0.   1.   2.  ]


##### random 生成随机数

In [9]:
nd2 = np.random.random([3,3])
print(nd2, nd2.shape)

np.random.seed(123)
nd3 = np.random.randn(2,3)
print(nd3)
np.random.shuffle(nd3)
print(nd3)

[[0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]] (3, 3)
[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]


##### 生成特定的矩阵

In [14]:
nd4 = np.zeros((3,4))
nd5 = np.zeros_like(nd4)
nd6 = np.ones((2,3))
nd7 = np.eye(3)
nd8 = np.diag([1,2,3])

print(nd4)
print(nd5)
print(nd6)
print(nd7)
print(nd8)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


##### 保存暂时的数据到本地文件

In [15]:
nd9 = np.random.random([5,5])
np.savetxt(X=nd9, fname='./test1.txt')
nd10 = np.loadtxt('./test1.txt')
print(nd10)

[[0.41092437 0.5796943  0.13995076 0.40101756 0.62731701]
 [0.32415089 0.24475928 0.69475518 0.5939024  0.63179202]
 [0.44025718 0.08372648 0.71233018 0.42786349 0.2977805 ]
 [0.49208478 0.74029639 0.35772892 0.41720995 0.65472131]
 [0.37380143 0.23451288 0.98799529 0.76599595 0.77700444]]
